# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a32be33e9285150905734897472005e3e06b47c3827d04a34b8acc463ce68b2c8add2a089a6ac56a7c6b6e4b5f190caeb59491ba93b53f5c39aca537488c0249

test:
  secret_key_base: 41852f971b5bf484c88c2001fd24d11913973ff0a350939b88358ecb4f0c6affa9ee0569ca202ed99e407731bd86a2fa5b7a663d09ec2007ae4a76f2fa52da8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
